#!/usr/bin/env bash

## Wofi Dictionary

## Files
CONFIG="$HOME/.config/hypr/wofi/config"
STYLE="$HOME/.config/hypr/wofi/style.css"
COLORS="$HOME/.config/hypr/wofi/colors"

## Wofi Command
wofi_command="wofi -n --show dmenu \
			--conf ${CONFIG} --style ${STYLE} --color ${COLORS} \
			--width=1000 --height=500 \
			--cache-file=/dev/null \
			--hide-scroll --no-actions"

input="$(${wofi_command})"

trans $input -t zh | ${wofi_command}
