

times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.024  000.024: --- NVIM STARTING ---
022.007  021.982: locale set
022.701  000.694: inits 1
022.998  000.297: window checked
026.254  003.257: parsing arguments
026.342  000.088: expanding arguments
026.422  000.080: inits 2
028.915  002.494: init highlight
028.919  000.004: waiting for UI
032.389  003.469: done waiting for UI
032.420  000.032: init screen for UI
032.451  000.031: init default mappings
032.679  000.228: init default autocommands
050.814  002.054  002.054: sourcing C:\Users\cells\AppData\Local\nvim-data\site\autoload\plug.vim
079.081  000.138  000.138: sourcing C:\Users\cells\AppData\Local\nvim\plugged\csv.vim\ftdetect\csv.vim
082.008  000.132  000.132: sourcing C:\Users\cells\AppData\Local\nvim\plugged\LuaSnip\ftdetect\snippets.vim
083.403  016.793  016.523: sourcing C:\tools\neovim\Neovim\share\nvim\runtime\filetype.vim
084.359  000.105  000.105: sourcing C:\tools\neovim\Neovim\share\nvim\runtime\ftplugin.vim
088.409  000.153  000.153: sourcing C:\tools\neovim\Neovim\share\nvim\runtime\indent.vim
089.904  000.209  000.209: sourcing C:\tools\neovim\Neovim\share\nvim\runtime\syntax\synload.vim
090.133  001.398  001.189: sourcing C:\tools\neovim\Neovim\share\nvim\runtime\syntax\syntax.vim
094.193  061.172  040.669: sourcing C:\Users\cells\AppData\Local\nvim\init.lua
094.248  000.396: sourcing vimrc file(s)
098.409  000.183  000.183: sourcing C:/Users/cells/AppData/Local/nvim/plugged/plenary.nvim/plugin/plenary.vim
102.132  000.138  000.138: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nightfox.nvim/plugin/nightfox.vim
114.857  000.303  000.303: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/init.vim
120.298  000.200  000.200: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/parts.vim
123.961  000.137  000.137: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/formatter/short_path.vim
131.059  000.357  000.357: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/util.vim
131.183  024.157  023.161: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/plugin/airline.vim
134.631  000.145  000.145: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline-themes/plugin/airline-themes.vim
145.016  000.501  000.501: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/autoload/nerdtree.vim
151.299  000.558  000.558: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/path.vim
156.575  000.248  000.248: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/menu_controller.vim
161.743  000.199  000.199: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/menu_item.vim
166.878  000.236  000.236: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/key_map.vim
172.326  000.342  000.342: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/bookmark.vim
178.032  000.341  000.341: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/tree_file_node.vim
184.304  000.548  000.548: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/tree_dir_node.vim
191.536  000.310  000.310: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/opener.vim
197.371  000.381  000.381: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/creator.vim
202.022  000.170  000.170: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/flag_set.vim
207.612  000.242  000.242: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/nerdtree.vim
212.927  000.452  000.452: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/ui.vim
216.508  000.154  000.154: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/event.vim
220.487  000.170  000.170: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/lib/nerdtree/notifier.vim
226.145  000.593  000.593: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/autoload/nerdtree/ui_glue.vim
239.363  000.222  000.222: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/nerdtree_plugin/exec_menuitem.vim
287.140  027.171  027.171: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/autoload/provider/clipboard.vim
287.552  042.427  015.256: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/nerdtree_plugin/fs_menu.vim
291.468  000.178  000.178: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/nerdtree_plugin/vcs.vim
292.880  153.512  105.240: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdtree/plugin/NERD_tree.vim
299.135  001.998  001.998: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-sneak/plugin/sneak.vim
304.767  000.648  000.648: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-surround/plugin/surround.vim
313.213  000.555  000.555: sourcing C:/Users/cells/AppData/Local/nvim/plugged/auto-pairs/plugin/auto-pairs.vim
321.381  000.305  000.305: sourcing C:/Users/cells/AppData/Local/nvim/plugged/ctrlp.vim/autoload/ctrlp/mrufiles.vim
321.652  004.836  004.531: sourcing C:/Users/cells/AppData/Local/nvim/plugged/ctrlp.vim/plugin/ctrlp.vim
329.384  002.912  002.912: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nerdcommenter/plugin/nerdcommenter.vim
334.428  000.409  000.409: sourcing C:/Users/cells/AppData/Local/nvim/plugged/tabular/plugin/Tabular.vim
345.237  000.844  000.844: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vimwiki/autoload/vimwiki/vars.vim
352.629  000.372  000.372: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vimwiki/autoload/vimwiki/u.vim
355.851  016.693  015.476: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vimwiki/plugin/vimwiki.vim
360.490  000.411  000.411: sourcing C:/Users/cells/AppData/Local/nvim/plugged/csv.vim/plugin/csv.vim
429.849  065.565  065.565: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nvim-lspconfig/plugin/lspconfig.vim
435.305  000.400  000.400: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nvim-lsp-installer/plugin/nvim-lsp-installer.vim
462.940  023.198  023.198: sourcing C:/Users/cells/AppData/Local/nvim/plugged/LuaSnip/plugin/luasnip.vim
468.683  000.485  000.485: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/gzip.vim
471.103  000.121  000.121: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/health.vim
474.203  000.236  000.236: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/man.vim
484.574  000.603  000.603: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/pack/dist/opt/matchit/plugin/matchit.vim
484.950  008.485  007.883: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/matchit.vim
489.976  000.501  000.501: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/matchparen.vim
495.462  000.852  000.852: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/netrwPlugin.vim
502.565  000.123  000.123: sourcing C:\Users\cells\AppData\Local/nvim-data/rplugin.vim
502.604  003.075  002.952: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/rplugin.vim
506.105  000.290  000.290: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/shada.vim
509.157  000.156  000.156: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/spellfile.vim
512.384  000.329  000.329: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/tarPlugin.vim
516.449  000.260  000.260: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/tohtml.vim
519.532  000.149  000.149: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/tutor.vim
522.687  000.344  000.344: sourcing C:/tools/neovim/Neovim/share/nvim/runtime/plugin/zipPlugin.vim
538.836  012.803  012.803: sourcing C:/Users/cells/AppData/Local/nvim/plugged/nvim-cmp/plugin/cmp.lua
539.830  121.737: loading rtp plugins
540.246  000.416: loading packages
550.490  000.533  000.533: sourcing C:/Users/cells/AppData/Local/nvim/plugged/tabular/autoload/tabular.vim
552.166  007.455  006.922: sourcing C:/Users/cells/AppData/Local/nvim/plugged/tabular/after/plugin/TabularMaps.vim
564.230  008.075  008.075: sourcing C:/Users/cells/AppData/Local/nvim/plugged/cmp-nvim-lsp/after/plugin/cmp_nvim_lsp.lua
598.184  031.131  031.131: sourcing C:/Users/cells/AppData/Local/nvim/plugged/cmp-buffer/after/plugin/cmp_buffer.lua
605.231  004.287  004.287: sourcing C:/Users/cells/AppData/Local/nvim/plugged/cmp-path/after/plugin/cmp_path.lua
612.357  004.332  004.332: sourcing C:/Users/cells/AppData/Local/nvim/plugged/cmp-cmdline/after/plugin/cmp_cmdline.lua
618.831  003.741  003.741: sourcing C:/Users/cells/AppData/Local/nvim/plugged/cmp-spell/after/plugin/cmp-spell.lua
626.614  004.790  004.790: sourcing C:/Users/cells/AppData/Local/nvim/plugged/cmp_luasnip/after/plugin/cmp_luasnip.lua
626.632  022.575: loading after plugins
626.665  000.034: inits 3
631.342  004.677: reading ShaDa
637.447  000.860  000.860: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions.vim
641.922  000.248  000.248: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/quickfix.vim
647.509  000.503  000.503: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline.vim
651.862  000.224  000.224: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/netrw.vim
660.797  000.269  000.269: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/section.vim
666.835  000.576  000.576: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/highlighter.vim
667.201  011.123  010.278: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/term.vim
671.924  000.220  000.220: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/ctrlp.vim
676.237  000.193  000.193: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/csv.vim
680.801  000.230  000.230: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/nvimlsp.vim
685.820  000.346  000.346: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/whitespace.vim
699.518  000.223  000.223: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/po.vim
704.829  000.266  000.266: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/wordcount.vim
708.748  000.200  000.200: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/keymap.vim
713.449  000.210  000.210: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/searchcount.vim
748.892  000.235  000.235: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/themes.vim
749.462  006.318  006.083: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/themes/dark.vim
773.355  000.321  000.321: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/builder.vim
778.321  000.255  000.255: sourcing C:/Users/cells/AppData/Local/nvim/plugged/vim-airline/autoload/airline/extensions/default.vim
791.040  137.959: opening buffers
792.267  001.226: BufEnter autocommands
792.272  000.005: editing files in windows
792.502  000.230: VimEnter autocommands
792.507  000.005: UIEnter autocommands
792.512  000.005: before starting main loop
1725.476  932.964: first screen update
1725.483  000.007: --- NVIM STARTED ---
