#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="youtube-dl --add-metadata -i" \
	yta="yt-dlp -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner" \
  trans="trans -t zh"

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	ll="ls -lhN --color=auto --group-directories-first" \
	la="ls -lhNa --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
  # v="fd --type f --hidden --exclude .git | fzf-tmux -p --reverse --preview 'cat {}' | xargs lvim" \
  # ii="cd `fd --type d --hidden --exclude .git | fzf-tmux -p --reverse`" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
    cl="calcurse" \
    view="nvim -R"

alias \
	lf="lfub" \
	magit="nvim -c MagitOnly" \
	ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc" \
	weath="less -S ${XDG_DATA_HOME:-$HOME/.local/share}/weatherreport" 

# fzf shortcut

# fzf and open file in current directory 
v() {
  file=$(fd --type f --hidden --exclude .git | fzf )
  [ -f "$file" ] && $EDITOR "$file"
}
# fzf and cd into directory
ff() {
  dir=$(fd --type d --hidden | fzf )
  [ -d $dir ] && cd $dir && ls
}

# fzf and open configs
fc() {
  file=$(fd . $HOME/.config/ $HOME/dotfiles/ --type f --hidden | fzf )
  [ -f "$file" ] && $EDITOR "$file"
}

