format = "$time $username$hostname $directory$git_branch[⚡ ](bold green)"

[git_branch]
style = "bold green"
format = "[\\([$branch$tag](bold green)\\)](bold white)"

[git_status]
format = ' ([\[$conflicted$deleted$renamed$modified$staged$untracked$ahead_behind\]]($style))'

[directory]
style = "bold blue"
truncate_to_repo = false
truncation_length = 1
fish_style_pwd_dir_length = 1

[python]
scan_for_pyfiles = false

[ruby]
disabled = true

[swift]
disabled = true

[hostname]
ssh_only = true
format = "`@`[$hostname]($style)"
style = "bold white"

[username]
show_always = false
style_user = "bold yellow"
format = "[$user]($style)"

[time]
disabled = false
format = "[$time]($style)"
time_format = "%H:%M"
